services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    ports:
      - "${MONGODB_PORT}:27017"

  website:
    image: myrustblog:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017
      - RUST_LOG=${RUST_LOG}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - NEW_USER_DEFAULT_ROLE=${NEW_USER_DEFAULT_ROLE}
      - WEBSITE_URL=${WEBSITE_URL}
      - RSS_TITLE=${RSS_TITLE}
      - RSS_DESCRIPTION=${RSS_DESCRIPTION}
    ports:
      - "${WEBSITE_PORT}:8081"

volumes:
  mongodb_data:
